from generator.html_assembler import HTMLAssembler


def test_drive_descriptions_include_popup_url_when_available() -> None:
    assembler = HTMLAssembler.__new__(HTMLAssembler)
    destinations = [
        {
            "scenic_drives": [
                {
                    "title": "Zion Canyon Scenic Drive",
                    "category": "scenic_drive",
                    "distance_or_duration": "54 mi",
                    "best_time": "Morning",
                    "description": "Classic canyon drive.",
                    "vehicle_requirement": "any",
                    "url": "https://example.com/should-not-render",
                }
            ]
        }
    ]

    payload = assembler._build_drive_descriptions(destinations)

    assert payload["Zion Canyon Scenic Drive"].get("url") == "https://example.com/should-not-render"


def test_drive_descriptions_omit_popup_url_when_unsafe() -> None:
    assembler = HTMLAssembler.__new__(HTMLAssembler)
    destinations = [
        {
            "scenic_drives": [
                {
                    "title": "Unsafe Drive",
                    "category": "scenic_drive",
                    "distance_or_duration": "18 mi",
                    "best_time": "Morning",
                    "description": "Unsafe link test.",
                    "vehicle_requirement": "any",
                    "url": "javascript:alert(1)",
                }
            ]
        }
    ]

    payload = assembler._build_drive_descriptions(destinations)

    assert "url" not in payload["Unsafe Drive"]


def test_scenic_drive_card_uses_teaser_while_popup_keeps_full_description() -> None:
    assembler = HTMLAssembler.__new__(HTMLAssembler)
    drives = [
        {
            "title": "Zion Canyon Scenic Drive",
            "category": "drive",
            "distance_or_duration": "54 mi",
            "description": "First sentence teaser. Second sentence detailed popup guidance.",
        }
    ]

    html = assembler._build_attractions({"top_attractions": []}, drives=drives, dest_name="Zion National Park")
    payload = assembler._build_drive_descriptions([{"scenic_drives": drives}])

    assert "First sentence teaser." in html
    assert "Second sentence detailed popup guidance." not in html
    assert payload["Zion Canyon Scenic Drive"]["description"] == (
        "First sentence teaser. Second sentence detailed popup guidance."
    )


def test_assembled_html_omits_attribution_footer(tmp_path) -> None:
    assembler = HTMLAssembler(config_path="config.yaml")
    trip = {
        "trip": {
            "title": "Test Trip",
            "theme_color": "#C0623E",
        },
        "_meta": {
            "generator_version": "test",
            "template_version": "test",
            "generated_at_utc": "2026-07-24T00:00:00+00:00",
            "llm": {"provider": "openai", "model": "test", "usage": {"models": [], "total_estimated_cost_usd": 0.0}},
        },
        "destinations": [],
    }

    html = assembler.assemble(trip)

    assert "id=\"attribution-block\"" not in html
    assert "Attribution &amp; Version Information" not in html


def test_assembled_html_includes_generator_footer_signature() -> None:
    assembler = HTMLAssembler(config_path="config.yaml")
    trip = {
        "trip": {
            "title": "Test Trip",
            "theme_color": "#C0623E",
        },
        "_meta": {
            "generator_version": "9.9.9",
            "template_version": "2.5",
            "generated_at_utc": "2026-07-26T17:41:23+00:00",
            "llm": {"provider": "openai", "model": "test", "usage": {"models": [], "total_estimated_cost_usd": 0.0}},
        },
        "destinations": [],
    }

    html = assembler.assemble(trip)

    assert "Generated by" in html
    assert "Road Trip Itinerary Generator" in html
    assert "v9.9.9" in html
    assert "Itinerary output: 2026-07-26 17:41 UTC" in html


def test_footer_issue_guidance_is_split_and_template_specific() -> None:
    assembler = HTMLAssembler(config_path="config.yaml")
    trip = {
        "trip": {
            "title": "Test Trip",
            "theme_color": "#C0623E",
        },
        "_meta": {
            "generator_version": "9.9.9",
            "template_version": "2.5",
            "generated_at_utc": "2026-07-26T17:41:23+00:00",
            "llm": {"provider": "openai", "model": "test", "usage": {"models": [], "total_estimated_cost_usd": 0.0}},
        },
        "destinations": [],
    }

    html = assembler.assemble(trip)

    assert "Issue reporting:" in html
    assert "?template=broken-link-report.yml&labels=bug" in html
    assert "?template=itinerary-feedback.yml" in html


def test_image_gallery_uses_unified_tile_structure() -> None:
    assembler = HTMLAssembler.__new__(HTMLAssembler)
    images = [
        {"local_path": "output/images/hero.jpg", "credit": "Hero"},
        {"local_path": "output/images/one.jpg", "credit": "Photo One"},
    ]

    html = assembler._build_image_gallery(images, "Zion National Park")

    assert '<div class="image-tile photo-item">' in html
    assert '<div class="caption photo-caption">Photo One</div>' in html
    assert 'onerror="this.style.display=\'none\';"' in html
    assert "<p class=\"photo-caption\">" not in html


def test_weather_url_uses_weather_gov_for_us_coordinates() -> None:
    assembler = HTMLAssembler.__new__(HTMLAssembler)
    url = assembler._build_weather_url({"lat": 37.2982, "lng": -113.0263})
    assert "forecast.weather.gov" in url


def test_weather_url_uses_global_fallback_for_non_us_coordinates() -> None:
    assembler = HTMLAssembler.__new__(HTMLAssembler)
    url = assembler._build_weather_url({"lat": 45.8150, "lng": 15.9819})
    assert "weather.com/weather/today/l/" in url


def test_build_map_markers_includes_sequential_stop_indices() -> None:
    assembler = HTMLAssembler.__new__(HTMLAssembler)
    destinations = [
        {"name": "Zion National Park", "dates": "October 7-9, 2026", "lat": 37.3, "lng": -113.0},
        {"name": "Bryce Canyon National Park", "dates": "October 10-12, 2026", "lat": 37.6, "lng": -112.2},
    ]
    trip_meta = {
        "departure": "Las Vegas",
        "departure_lat": 36.17,
        "departure_lng": -115.14,
        "return": "Salt Lake City",
        "return_lat": 40.76,
        "return_lng": -111.89,
    }

    markers = assembler._build_map_markers(destinations, trip_meta)
    dest_markers = [m for m in markers if "idx" in m]

    assert [m["idx"] for m in dest_markers] == [1, 2]
    assert [m["stop_index"] for m in dest_markers] == [1, 2]
    assert markers[0]["mo"] == "DEP"
    assert markers[-1]["mo"] == "RET"


def test_assembled_html_preserves_marker_date_context_alongside_stop_indices() -> None:
    assembler = HTMLAssembler(config_path="config.yaml")
    trip = {
        "trip": {
            "title": "Test Trip",
            "theme_color": "#C0623E",
            "departure": "Las Vegas",
            "departure_lat": 36.17,
            "departure_lng": -115.14,
            "return": "Salt Lake City",
            "return_lat": 40.76,
            "return_lng": -111.89,
        },
        "_meta": {
            "generator_version": "9.9.9",
            "template_version": "2.5",
            "generated_at_utc": "2026-07-26T17:41:23+00:00",
            "llm": {"provider": "openai", "model": "test", "usage": {"models": [], "total_estimated_cost_usd": 0.0}},
        },
        "destinations": [
            {
                "id": "zion",
                "name": "Zion National Park",
                "dates": "October 7-9, 2026",
                "lat": 37.3,
                "lng": -113.0,
                "images": [],
                "planning_links": [],
                "ai_content": {"top_attractions": [], "getting_here": {}, "possible_daily_schedule": [], "dinner_recommendations": []},
                "what_to_know": {
                    "summary": "Summary.",
                    "local_customs": "Customs.",
                    "best_times_of_day": "Morning.",
                    "transportation_quirks": "Transit.",
                    "safety_considerations": "Safety.",
                    "crowd_patterns": "Crowds.",
                    "local_etiquette": "Etiquette.",
                },
                "cultural_events": {"has_events": False, "events": []},
                "scenic_drives": [],
            }
        ],
    }

    html = assembler.assemble(trip)

    assert '"stop_index": 1' in html
    assert '"mo": "Oct"' in html
    assert '"dy": "7"' in html
    assert "var dateLabel = ((s.mo || '') + (s.dy ? (' ' + s.dy) : '')).trim();" in html
    assert "var markerDateSecondary = dateLabel" in html
    assert "width:34px;height:34px" in html
    assert "iconSize:[34,62],iconAnchor:[17,17],popupAnchor:[0,-22]" in html


def test_build_getting_there_renders_departure_route_options() -> None:
    assembler = HTMLAssembler.__new__(HTMLAssembler)
    ai = {
        "getting_there": {
            "route_summary": "Departure leg toward Albuquerque, NM.",
            "route_options": [
                {
                    "title": "Turquoise Trail Scenic Byway",
                    "distance_or_duration": "50 miles one-way",
                    "description": "Historic route via Madrid.",
                    "url": "https://example.com/turquoise-trail-byway",
                }
            ],
        }
    }
    dest = {"name": "Santa Fe"}
    trip_meta = {"return": "Albuquerque, NM"}

    html = assembler._build_getting_there(ai, dest, trip_meta)

    assert "Getting There" in html
    assert "Turquoise Trail Scenic Byway" in html
    assert "Departure leg toward Albuquerque, NM." in html


def test_intro_note_omits_weather_and_photography_rows() -> None:
    assembler = HTMLAssembler.__new__(HTMLAssembler)
    dest = {
        "name": "Zion National Park",
        "what_to_know": {
            "summary": "A summary.",
            "local_customs": "Customs.",
            "best_times_of_day": "Morning.",
            "typical_weather_patterns": "Cool nights.",
            "transportation_quirks": "Shuttle required.",
            "safety_considerations": "Carry water.",
            "photography_tips": "Bring a polarizer.",
            "crowd_patterns": "Busy weekends.",
            "local_etiquette": "Stay on trail.",
        },
    }
    html = assembler._build_intro_note(dest, events={})

    assert "Local customs:" in html
    assert "Best times of day:" in html
    assert "Transportation quirks:" in html
    assert "Safety:" in html
    assert "Crowd patterns:" in html
    assert "Local etiquette:" in html
    assert "Typical weather:" not in html
    assert "Photography:" not in html


def test_intro_note_does_not_repeat_fallback_cultural_events_copy() -> None:
    assembler = HTMLAssembler.__new__(HTMLAssembler)
    dest = {
        "name": "St. George",
        "what_to_know": {
            "summary": "Desert gateway with easy access to red-rock parks.",
            "local_customs": "Expect a relaxed pace in town.",
            "best_times_of_day": "Morning and dusk.",
            "transportation_quirks": "Parking is easiest outside midday.",
            "safety_considerations": "Carry water.",
            "crowd_patterns": "Busy on weekends.",
            "local_etiquette": "Respect trail signage.",
        },
    }
    events = {
        "has_events": False,
        "honest_assessment": "St. George has a lively cultural scene in October, characterized by community gatherings and outdoor activities.",
        "local_tip": "Check the local farmers market on Saturday mornings.",
    }

    html = assembler._build_intro_note(dest, events)

    assert "Desert gateway with easy access to red-rock parks." in html
    assert "St. George has a lively cultural scene in October" not in html
    assert "Local tip:" not in html


def test_image_caption_drops_wikimedia_template_boilerplate() -> None:
    assembler = HTMLAssembler.__new__(HTMLAssembler)
    image = {
        "credit": "<table><tr><td>When reusing, please credit me as ... external text href='https://commons.wikimedia.org/wiki/File:foo'</td></tr></table>",
        "source": "wikimedia",
        "title": "Bryce Canyon in Winter",
    }

    caption = assembler._build_image_caption(image)

    assert "Wikimedia" in caption
    assert "Bryce Canyon in Winter" in caption
    assert "<table" not in caption
    assert "external text" not in caption.lower()


def test_header_links_omit_invalid_urls_and_use_noopener() -> None:
    assembler = HTMLAssembler(config_path="config.yaml")
    dest = {"lat": 37.2982, "lng": -113.0263}
    links = [
        {"label": "Valid Plan", "url": "example.com/plan"},
        {"label": "Bad Link", "url": "javascript:alert(1)"},
        {"label": "Bad Link 2", "url": "data:text/html;base64,AAAA"},
    ]

    html = assembler._build_header_links(links, nps_code=None, dest=dest)

    assert "Valid Plan" in html
    assert "Bad Link" not in html
    assert "Bad Link 2" not in html
    assert 'target="_blank" rel="noopener"' in html


def test_build_attractions_fallback_maps_uses_destination_name() -> None:
    assembler = HTMLAssembler.__new__(HTMLAssembler)
    ai = {
        "top_attractions": [
            {
                "name": "Queens Garden Trail",
                "type": "hike",
                "description": "Popular canyon trail.",
                "url": "",
            }
        ]
    }

    html = assembler._build_attractions(ai, drives=[], dest_name="Bryce Canyon National Park")

    assert "google.com/maps/search/?api=1&amp;query=Queens%20Garden%20Trail%20Bryce%20Canyon%20National%20Park" in html


def test_build_attractions_fallback_maps_avoids_contradictory_destination_append() -> None:
    assembler = HTMLAssembler.__new__(HTMLAssembler)
    ai = {
        "top_attractions": [
            {
                "name": "Historic Downtown St. George",
                "type": "attraction",
                "description": "Historic district walk.",
                "url": "",
            }
        ]
    }

    html = assembler._build_attractions(ai, drives=[], dest_name="Zion National Park")

    assert "Historic%20Downtown%20St.%20George" in html
    assert "Zion%20National%20Park" not in html


def test_build_restaurants_prefers_discovered_url_over_maps_query() -> None:
    assembler = HTMLAssembler.__new__(HTMLAssembler)
    ai = {
        "dinner_recommendations": [
            {
                "name": "Tandoor Indian Cuisine",
                "url": "https://www.tripadvisor.com/Restaurant_Review-g57119-d1234567-Reviews-Tandoor_Indian_Cuisine-St_George_Utah.html",
                "maps_url": "https://www.google.com/maps/search/?api=1&query=Tandoor%20Indian%20Cuisine%20St.%20George%2C%20Utah",
                "cuisine": "Indian",
                "description": "Popular local Indian spot.",
            }
        ]
    }

    html = assembler._build_restaurants(ai, dest_name="St. George, Utah")

    assert "tripadvisor.com" in html
    assert "google.com/maps/search/?api=1&amp;query=Tandoor" not in html


def test_build_restaurants_uses_maps_url_when_no_discovered_url() -> None:
    assembler = HTMLAssembler.__new__(HTMLAssembler)
    ai = {
        "dinner_recommendations": [
            {
                "name": "Tandoor Indian Cuisine",
                "url": "",
                "maps_url": "https://www.google.com/maps/search/?api=1&query=Tandoor%20Indian%20Cuisine%20St.%20George%2C%20Utah",
                "cuisine": "Indian",
                "description": "Popular local Indian spot.",
            }
        ]
    }

    html = assembler._build_restaurants(ai, dest_name="St. George, Utah")

    assert "google.com/maps/search/?api=1&amp;query=Tandoor%20Indian%20Cuisine%20St.%20George%2C%20Utah" in html


def test_build_restaurants_avoids_rendering_maps_directions_url() -> None:
    assembler = HTMLAssembler.__new__(HTMLAssembler)
    ai = {
        "dinner_recommendations": [
            {
                "name": "Bit & Spur Restaurant & Saloon",
                "url": "https://www.google.com/maps/dir//Bit+%26+Spur+Restaurant+%26+Saloon,+1212+Zion+Park+Blvd,+Springdale,+UT+84767",
                "maps_url": "https://www.google.com/maps/search/?api=1&query=Bit%20%26%20Spur%20Restaurant%20%26%20Saloon%20Springdale",
                "cuisine": "Southwestern",
                "description": "Popular Springdale dinner spot.",
            }
        ]
    }

    html = assembler._build_restaurants(ai, dest_name="Zion National Park")

    assert "google.com/maps/dir/" not in html
    assert "google.com/maps/search/?api=1&amp;query=Bit%20%26%20Spur%20Restaurant%20%26%20Saloon%20Springdale" in html